### ISSUE TITLE
When installing the TASMOTA with TLS support and clicking enable TLS with GUI ''MQTT TLS'' option it does not work.

### ISSUE THREAD

**Issue by Nikoolayy1** [Jason2866/Tasmota-specials#9]
First thanks for the precompiled tasmota software.

I installed TASMOTA with TLS support on Sonoff basic smart switch and  when clicking enable TLS with GUI ''MQTT TLS'' option it does not work as the device reboots and option is cleared for some reason even after enabling it before the reboot (as enabling it causes the reboot). The workaround is from the TASMOTA console to set the option with "SetOption103 1".

https://tasmota.github.io/docs/Commands/

**Comment by Jason2866** [comment]
Can you try with a NodeMCU? The power supply of many sonoff devices is borderline.
Using TLS needs a lot of MCU (=more current) and this can be to much for a sonoff device.
Resulting in what you are encounter.

**Comment by Nikoolayy1** [comment]
But with option 103 it works as I mentioned?

На сб, 3.07.2021 г., 16:16 ч. Jason2866 ***@***.***> написа:

**Comment by Jason2866** [comment]
When power supply is the reason, the rendering of the web page could be to much already.
Anyway it is not a issue of the build. If the NodeMCU test also fails please switch to Tasmota issues.

**Comment by Nikoolayy1** [comment]
Thanks. Yes   the issue  probably is with power or Tasmota issue in
general. I am also mentioning this just so that there is a workaround, so
who has the same issue, they can try the workaround.

На сб, 3.07.2021 г. в 17:48 ч. Jason2866 ***@***.***> написа:
